### ISSUE TITLE
Runtime Error? 

### ISSUE THREAD

**Issue by usamamuneerchaudhary** [phpgl/flappyphpant#3]
Hey, real nice game, well done :) 

While running `bash bin/play` command, I get the following error: 

```
bin/play: line 2: ?php: No such file or directory
bin/play: line 4: syntax error near unexpected token `'DS''
bin/play: line 4: `if (!defined('DS')) { define('DS', DIRECTORY_SEPARATOR); }'
```

They way I solve it: 
Install the `phpglfw` library by running: 
```
 php -r "copy('https://raw.githubusercontent.com/mario-deluna/php-glfw/master/install/macos-installer.php', 'phpglfw-installer.php');" && php phpglfw-installer.php
```

and finally instead of bash, I tried with `php bin/play` and it ran.

**Comment by SezerFidanci** [comment]
thanks @usamamuneerchaudhary 
see also manuel installation or other os installation : https://phpgl.net/getting-started/installation/install-macos.html

**Comment by mario-deluna** [comment]
Thanks, I clarified the installation instructions in the README: https://github.com/phpgl/flappyphpant/commit/e07d0187adb1d9ef75f523ff61fce2c5ae470963
