### ISSUE TITLE
Didn't run on macos 15.1

### ISSUE THREAD

**Issue by Yur-ok** [phpgl/flappyphpant#6]
<img width="736" alt="image" src="https://github.com/user-attachments/assets/6fd57a16-4949-42d4-bdfa-2f76f23cd40e">

**Comment by mario-deluna** [comment]
@Yur-ok It looks like the shebang is not properly interpreted. 

You should be able to simply run it with php:

```
php bin/play
```

**Comment by Yur-ok** [comment]
@mario-deluna Thx!
Yes it works!
But I did like instructions said.
